#include "SensorSimulator.h"
#include <cmath>
#include <algorithm>

// ============================================================
//  CONSTRUCTOR
// ============================================================
SensorSimulator::SensorSimulator(float initialBatteryTemp,
                                 float initialAmbientTemp,
                                 float initialSoC)
    : batteryTemp_(initialBatteryTemp)
    , ambientTemp_(initialAmbientTemp)
    , stateOfCharge_(initialSoC)
    , coolantTemp_(initialAmbientTemp)
    , tickCount_(0)
    , initBatteryTemp_(initialBatteryTemp)
    , initAmbientTemp_(initialAmbientTemp)
    , initSoC_(initialSoC)
    , rng_(std::random_device{}())
    , noiseDist_(0.0f, 1.0f)
{
}

// ============================================================
//  UPDATE — call every simulation tick
//  deltaTimeSeconds: how much sim time has passed (e.g. 0.1s)
// ============================================================
SensorReading SensorSimulator::update(float vehicleSpeedKph,
                                       float deltaTimeSeconds) {
    tickCount_++;

    // --- 1. Compute heat generated by battery this tick ---
    float heatGen = computeHeatGeneration(vehicleSpeedKph, stateOfCharge_);

    // --- 2. Natural cooling toward ambient (passive) ---
    float passiveCooling = computeCooling(batteryTemp_, ambientTemp_, 0.0f);

    // --- 3. Update battery temperature ---
    batteryTemp_ += (heatGen - passiveCooling) * deltaTimeSeconds;

    // --- 4. Clamp temperature to physical limits ---
    batteryTemp_ = std::clamp(batteryTemp_, -30.0f, 90.0f);

    // --- 5. Drain SoC based on speed (higher speed = more draw) ---
    float dischargRate = 0.002f + (vehicleSpeedKph / 200.0f) * 0.01f;
    stateOfCharge_ -= dischargRate * deltaTimeSeconds;
    stateOfCharge_ = std::clamp(stateOfCharge_, 0.0f, 1.0f);

    // --- 6. Coolant temp moves toward battery temp slowly ---
    coolantTemp_ += (batteryTemp_ - coolantTemp_) * 0.05f * deltaTimeSeconds;

    // --- 7. Build the SensorReading struct ---
    SensorReading reading;
    reading.timestampMs       = tickCount_ * static_cast<uint32_t>(deltaTimeSeconds * 1000);
    reading.vehicleSpeedKph   = vehicleSpeedKph + addNoise(0.0f, 0.5f);

    // Battery state — add small noise to each sensor value
    reading.battery.temperature   = batteryTemp_  + addNoise(0.0f, 0.3f);
    reading.battery.stateOfCharge = stateOfCharge_;
    reading.battery.voltage       = 350.0f + stateOfCharge_ * 50.0f + addNoise(0.0f, 0.5f);
    reading.battery.current       = 20.0f  + (vehicleSpeedKph / 200.0f) * 180.0f + addNoise(0.0f, 1.0f);
    reading.battery.isCharging    = false;

    // Thermal state
    reading.thermal.ambientTemperature = ambientTemp_ + addNoise(0.0f, 0.2f);
    reading.thermal.coolantTemperature = coolantTemp_ + addNoise(0.0f, 0.3f);
    reading.thermal.fanSpeedPercent    = 0.0f;  // Controller sets this later
    reading.thermal.pumpActive         = false;  // Controller sets this later
    reading.thermal.heaterActive       = false;  // Controller sets this later

    return reading;
}

// ============================================================
//  RESET — restore initial conditions
// ============================================================
void SensorSimulator::reset() {
    batteryTemp_    = initBatteryTemp_;
    ambientTemp_    = initAmbientTemp_;
    stateOfCharge_  = initSoC_;
    coolantTemp_    = initAmbientTemp_;
    tickCount_      = 0;
}

// ============================================================
//  PHYSICS: heat generation
//  Higher speed + lower SoC = more heat produced
// ============================================================
float SensorSimulator::computeHeatGeneration(float speedKph,
                                              float socFraction) {
    // Base heat from motor load (speed-dependent)
    float motorHeat = (speedKph / 200.0f) * 8.0f;

    // Extra heat when battery is low (internal resistance rises)
    float resistanceHeat = (1.0f - socFraction) * 2.0f;

    return motorHeat + resistanceHeat;
}

// ============================================================
//  PHYSICS: passive cooling toward ambient
// ============================================================
float SensorSimulator::computeCooling(float battTemp,
                                       float ambientTemp,
                                       float fanSpeed) {
    // Passive cooling — proportional to temp difference
    float delta = battTemp - ambientTemp;
    float passive = delta * 0.08f;

    // Active cooling from fan (used later by controller)
    float active = fanSpeed * delta * 0.15f;

    return passive + active;
}

// ============================================================
//  NOISE — Gaussian noise to simulate real sensor imprecision
// ============================================================
float SensorSimulator::addNoise(float value, float magnitude) {
    return value + noiseDist_(rng_) * magnitude;
}